spring.application.name=server-management
server.port=26900

servers.server-list[0].apiUrl=http://localhost:9991/management
servers.server-list[0].startCommand=cmd.exe /c start C:\\Users\\Tobias\\Tools\\wildfly-40.0.0.Final\\bin\\standalone.bat -Djboss.socket.binding.port-offset=1
servers.server-list[0].username=admin
servers.server-list[0].password=admin1234
servers.server-list[0].tag=ConPlus Portal

servers.server-list[1].apiUrl=http://localhost:9992/management
servers.server-list[1].startCommand=cmd.exe /c start C:\\Users\\Tobias\\Tools\\wildfly-40.0.0.Final-2\\bin\\standalone.bat -Djboss.socket.binding.port-offset=2
servers.server-list[1].username=admin
servers.server-list[1].password=admin1234
servers.server-list[1].tag=ConPlus Remote

servers.server-list[2].apiUrl=http://localhost:9993/management
servers.server-list[2].startCommand=cmd.exe /c start C:\\Users\\Tobias\\Tools\\wildfly-40.0.0.Final-3\\bin\\standalone.bat -Djboss.socket.binding.port-offset=3
servers.server-list[2].username=admin
servers.server-list[2].password=admin1234
servers.server-list[2].tag=Batch

servers.server-list[3].apiUrl=http://localhost:9994/management
servers.server-list[3].startCommand=cmd.exe /c start C:\\Users\\Tobias\\Tools\\wildfly-40.0.0.Final-4\\bin\\standalone.bat -Djboss.socket.binding.port-offset=4
servers.server-list[3].username=admin
servers.server-list[3].password=admin1234
servers.server-list[3].tag=ConPlus Portal JBoss 8

servers.server-list[4].apiUrl=http://localhost:9995/management
servers.server-list[4].startCommand=cmd.exe /c start C:\\Users\\Tobias\\Tools\\wildfly-40.0.0.Final-5\\bin\\standalone.bat -Djboss.socket.binding.port-offset=5
servers.server-list[4].username=admin
servers.server-list[4].password=admin1234
servers.server-list[4].tag=ConPlus Remote JBoss 8

servers.server-list[5].apiUrl=http://localhost:9996/management
servers.server-list[5].startCommand=cmd.exe /c start C:\\Users\\Tobias\\Tools\\wildfly-40.0.0.Final-6\\bin\\standalone.bat -Djboss.socket.binding.port-offset=6
servers.server-list[5].username=admin
servers.server-list[5].password=admin1234
servers.server-list[5].tag=Batch JBoss 8